version: '3.7'
x-template-app: &app_base
  env_file:
    - .env
  build:
    context: .
    dockerfile: docker/app.dockerfile
  working_dir: /var/www
  volumes:
    - ./:/var/www
    - ./docker/php.ini:/usr/local/etc/php/php.ini
  depends_on:
    - redis
networks:
 my_net:
    ipam:
      config:
      - subnet: 172.32.0.0/24

services:
  app:
    <<: *app_base
    restart: always
    container_name: calladmin_app
    entrypoint: /entrypoint.sh
    networks:
      my_net:
        ipv4_address: 172.32.0.5
  web:
    restart: always
    build:
      context: .
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    container_name: calladmin_web
    ports:
      - 8090:90
    volumes:
      - ./:/var/www
    depends_on:
      - app
    networks:
      my_net:
        ipv4_address: 172.32.0.4

  redis:
    image: 'redis:latest'
    restart: always
    container_name: calladmin_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ./docker/redis_data:/bitnami/redis
    networks:
      my_net:
        ipv4_address: 172.32.0.3

  npm:
    image: node:12.18
    container_name: calladmin_npm
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: ['npm', '--no-bin-links']
    networks:
      my_net:
        ipv4_address: 172.32.0.2

  worker:
    <<: *app_base
    restart: always
    container_name: calladmin_worker
    entrypoint: ./docker/worker-entrypoint.sh
    networks:
      my_net:
        ipv4_address: 172.32.0.6

